### ISSUE TITLE
Clean Architecture

### ISSUE THREAD

**Issue by roswer13** [danroth27/BlazorWeather#17]
I really like this project, I think it's a good idea. 

But it is possible to create an architecture where a core behaves with a Blazor project and with a Maui project, check the following [link ](https://github.com/eduardomoroni/react-clean-architecture) that shows how you can use React Native with React Js in a single architecture.

Best regards.

**Comment by rogihee** [comment]
You lost me at Interactor. Or was it Reducer? 

I never worked with React but upon first glance there are so many files, arrows, folders and one-line index.ts files and export statements and just weird acronyms. Just....wow. 

Sorry, I don't want to judge too much and your comment is well intentioned, but this is definitely not for me.
