### ISSUE TITLE
Cannot run or compile app

### ISSUE THREAD

**Issue by mihaimyh** [danroth27/BlazorWeather#20]
I have a strange error, it saying I am missing .NET 6 SDK installed, although I have it.

![image](https://user-images.githubusercontent.com/549272/121783778-43b11880-cbb9-11eb-84c1-62562aa882de.png)

**Comment by mihaimyh** [comment]
It seems I didn't had .NET preview SDKs enabled on VS.

![image](https://user-images.githubusercontent.com/549272/121785469-97742f80-cbc2-11eb-81b3-2b86c312fc1f.png)

**Comment by danroth27** [comment]
@mihaimyh I'm glad you were able to figure this issue out! Please note that we generally recommend using .NET 6 previews with the latest Visual Studio preview: https://visualstudio.com/preview. Preview releases of Visual Studio support preview .NET SDKs by default.
