### ISSUE TITLE
Online Demo Link Broken?

### ISSUE THREAD

**Issue by bigredky** [danroth27/BlazorWeather#23]
We've been watching this repo so we can start reusing as it approaches later previews. 

I was going to show this to some other team members but looks like the repo demo link is not working?

https://aka.ms/blazorweather

Is there another online URL where this demo can be hit rather than running the solution locally?

Thanks in advance.

**Comment by danroth27** [comment]
Hi @bigredky. I haven't deployed the new .NET 6 version of the app anywhere public yet unfortunately. The web app should be pretty easy to run locally though. For the .NET MAUI app, a bit more setup is required: https://docs.microsoft.com/dotnet/maui/get-started/installation.

**Comment by bigredky** [comment]
Gotcha. No worries. I'll do that. Have a good one.
