### ISSUE TITLE
need to install 2 preview extensions

### ISSUE THREAD

**Issue by AlexNek** [danroth27/BlazorWeather#31]
I download extension from the links but they try to install into VS 2019 preview not into VS 2022 preview.
I can build projects for Android and Windows  targets without it.
Do we really need this extensions for 2022 preview 4.1?

**Comment by danroth27** [comment]
Oh, sorry, the readme is really out of date. Let me fix that now.

**Comment by danroth27** [comment]
OK, should be cleaned up now. Sorry about the delay!

**Comment by AlexNek** [comment]
Thanks a lot for changing. Many people write - this is a demo project no changes to expect.
I will wait next VS 2022 release up to the new problems writing.

Could you give me a tip where can I ask a Blazor questions? Here I have no success:
[https://docs.microsoft.com/en-us/answers/questions/541604/blazor-hosted-webassembly-addidentityserveraddapia.html](https://docs.microsoft.com/en-us/answers/questions/541604/blazor-hosted-webassembly-addidentityserveraddapia.html)
I think this is related to the design concept.
