### ISSUE TITLE
BlazorWeather.Electron fails to load assembly Microsoft.AspNetCore.Components.Electron

### ISSUE THREAD

**Issue by dcuccia** [danroth27/BlazorWeather#4]
When building BlazorWeather.Electron, the package dependency Microsoft.AspNetCore.Components.Electron version 0.1.0-preview1 is not found.

Changing to version 0.1.0-dev seemed to get past this issue and complete build step (after installing nodejs global dependency). Running that, however, seems to hang and not show any UI, so hesitant to submit a PR. FWIW, here's the building BlazorWeather.Electron.csproj snippet:

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Electron" Version="0.1.0-dev" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.0.0" />
  </ItemGroup>
```

**Comment by prkhandelwal** [comment]
@dcuccia Try 0.1.0-alpha

**Comment by danroth27** [comment]
@dcuccia Sorry about that! Should be fixed now.

**Comment by dcuccia** [comment]
Thanks @danroth27 !
